name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Atau branch yang Anda gunakan untuk deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Tentukan versi PHP yang Anda inginkan

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader

      # Set up environment variables (optional)
      - name: Set up environment variables
        run: echo "APP_ENV=production" >> $GITHUB_ENV

      # Run database migrations (optional)
      - name: Run migrations
        run: php artisan migrate --force

      # Deploy to server (Contoh menggunakan SSH)
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /path/to/your/app
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
